### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by almarti** [idaviddesmet/MaffViewer#1]
I would really love to know how to use your maffviewer.  Can you please include more details on how to view maff files with your viewer.

Thanks,

Al

**Comment by daviddesmet** [comment]
Hello Al,

It is really simply, you just select the maff file and drag it onto the window.
Nonetheless, the app was created using the trial version of [DotNetBrowser](https://www.teamdev.com/dotnetbrowser) and it should be expired by now. I'm currently waiting for them to grant an open source license for the project, I already got a reply so it will be a matter of a couple of days for getting the license and applying the changes.

I will update you as soon as I receive it. If you in a rush, you could get a trial license and update the _teamdev.licenses_ file and compile the project. It should work without any issue ;-)

Final notes regarding the component (in case you're curious why I chose it). I've evaluated various components and found DotNetBrowser to be more MVVM friendly for WPF. I'm not related to the component nor the company behind it.

**Comment by daviddesmet** [comment]
Hello again Al!
Just to let you know that I've updated the code and the release so you will now be able to view the maff files ;-)

Will add later a video recording of how to use the tool if necessary.
